# Generated by Django 4.0 on 2024-06-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingmailing',
            name='status_attempt',
            field=models.BooleanField(default=True, max_length=10, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('создана', 'создана'), ('завершена', 'завершена'), ('запущена', 'запущена')], default='создана', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
