# Generated by Django 4.0 on 2024-06-18 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingmailing',
            name='status_attempt',
            field=models.BooleanField(default=False, max_length=10, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.Client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_mailing',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первой отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('создана', 'создана'), ('завершена', 'завершена'), ('запущена', 'запущена')], default='создана', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
