# Generated by Django 4.0 on 2024-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_loggingmailing_status_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingmailing',
            name='status_attempt',
            field=models.BooleanField(default=False, max_length=10, verbose_name='Статус попытки'),
        ),
    ]
