# Generated by Django 4.0 on 2024-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_loggingmailing_status_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.Client', verbose_name='Клиенты сервиса'),
        ),
    ]
