# Generated by Django 4.2.7 on 2024-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_end_mailing_mailing_next_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
