# Generated by Django 4.2.7 on 2024-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mailing_end_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена')], default='создана', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
