# Generated by Django 4.0 on 2024-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_client_comment_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.Client', verbose_name='Клиенты'),
        ),
    ]
