# Generated by Django 4.2.7 on 2024-06-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_client_owner_mailing_owner_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingmailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
